//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StockQuoteServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockQuoteServiceRef.IStockQuoteService")]
    public interface IStockQuoteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockQuoteService/StockQuote", ReplyAction="http://tempuri.org/IStockQuoteService/StockQuoteResponse")]
        string StockQuote(string stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockQuoteService/StockQuote", ReplyAction="http://tempuri.org/IStockQuoteService/StockQuoteResponse")]
        System.Threading.Tasks.Task<string> StockQuoteAsync(string stock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockQuoteServiceChannel : Client.StockQuoteServiceRef.IStockQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockQuoteServiceClient : System.ServiceModel.ClientBase<Client.StockQuoteServiceRef.IStockQuoteService>, Client.StockQuoteServiceRef.IStockQuoteService {
        
        public StockQuoteServiceClient() {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StockQuote(string stock) {
            return base.Channel.StockQuote(stock);
        }
        
        public System.Threading.Tasks.Task<string> StockQuoteAsync(string stock) {
            return base.Channel.StockQuoteAsync(stock);
        }
    }
}
